services:
  project-service:
    build: .
    ports:
      - "9400:9400"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://project:project@host.docker.internal:5433/project}
    volumes:
      - ./app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9400", "--reload"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
